2021-09-28 16:31:46,053 INFO    MainThread:3830 [wandb_setup.py:_flush():69] setting env: {}
2021-09-28 16:31:46,053 WARNING MainThread:3830 [wandb_setup.py:_flush():69] could not find program at scripts/train.py
2021-09-28 16:31:46,053 INFO    MainThread:3830 [wandb_setup.py:_flush():69] setting login settings: {}
2021-09-28 16:31:46,053 INFO    MainThread:3830 [wandb_init.py:_log_setup():348] Logging user logs to /home/bhuwan/Desktop/cat-dog/outputs/2021-09-28/16-31-45/wandb/run-20210928_163146-3lhyhwam/logs/debug.log
2021-09-28 16:31:46,053 INFO    MainThread:3830 [wandb_init.py:_log_setup():349] Logging internal logs to /home/bhuwan/Desktop/cat-dog/outputs/2021-09-28/16-31-45/wandb/run-20210928_163146-3lhyhwam/logs/debug-internal.log
2021-09-28 16:31:46,053 INFO    MainThread:3830 [wandb_init.py:init():381] calling init triggers
2021-09-28 16:31:46,053 INFO    MainThread:3830 [wandb_init.py:init():386] wandb.init called with sweep_config: {}
config: {'lr': 0.0003, 'base_filters': 32, 'epochs': 2}
2021-09-28 16:31:46,053 INFO    MainThread:3830 [wandb_init.py:init():430] starting backend
2021-09-28 16:31:46,053 INFO    MainThread:3830 [backend.py:_multiprocessing_setup():70] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2021-09-28 16:31:46,058 INFO    MainThread:3830 [backend.py:ensure_launched():135] starting backend process...
2021-09-28 16:31:46,062 INFO    MainThread:3830 [backend.py:ensure_launched():139] started backend process with pid: 3862
2021-09-28 16:31:46,063 INFO    MainThread:3830 [wandb_init.py:init():435] backend started and connected
2021-09-28 16:31:46,064 INFO    MainThread:3830 [wandb_init.py:init():494] updated telemetry
2021-09-28 16:31:46,064 INFO    MainThread:3830 [wandb_init.py:init():517] communicating current version
2021-09-28 16:31:46,588 INFO    MainThread:3830 [wandb_init.py:init():522] got version response 
2021-09-28 16:31:46,588 INFO    MainThread:3830 [wandb_init.py:init():530] communicating run to backend with 30 second timeout
2021-09-28 16:31:46,872 INFO    MainThread:3830 [wandb_init.py:init():557] starting run threads in backend
2021-09-28 16:31:50,869 INFO    MainThread:3830 [wandb_run.py:_console_start():1605] atexit reg
2021-09-28 16:31:50,869 INFO    MainThread:3830 [wandb_run.py:_redirect():1479] redirect: SettingsConsole.REDIRECT
2021-09-28 16:31:50,869 INFO    MainThread:3830 [wandb_run.py:_redirect():1484] Redirecting console.
2021-09-28 16:31:50,870 INFO    MainThread:3830 [wandb_run.py:_redirect():1540] Redirects installed.
2021-09-28 16:31:50,870 INFO    MainThread:3830 [wandb_init.py:init():582] run started, returning control to user process
2021-09-28 16:31:51,523 INFO    MainThread:3830 [wandb_run.py:_atexit_cleanup():1575] got exitcode: 0
2021-09-28 16:31:51,524 INFO    MainThread:3830 [wandb_run.py:_restore():1547] restore
2021-09-28 16:31:54,394 INFO    MainThread:3830 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 654
  total_bytes: 654
}

2021-09-28 16:31:54,768 INFO    MainThread:3830 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 654
  total_bytes: 654
}

2021-09-28 16:31:54,898 INFO    MainThread:3830 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 654
  total_bytes: 6445
}

2021-09-28 16:31:55,000 INFO    MainThread:3830 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 654
  total_bytes: 28063
}

2021-09-28 16:31:55,103 INFO    MainThread:3830 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 654
  total_bytes: 28063
}

2021-09-28 16:31:55,206 INFO    MainThread:3830 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 654
  total_bytes: 28063
}

2021-09-28 16:31:55,307 INFO    MainThread:3830 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 28063
  total_bytes: 28063
}

2021-09-28 16:31:55,410 INFO    MainThread:3830 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 28063
  total_bytes: 28063
}

2021-09-28 16:31:55,513 INFO    MainThread:3830 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 28063
  total_bytes: 28063
}

2021-09-28 16:31:55,616 INFO    MainThread:3830 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 28063
  total_bytes: 28063
}

2021-09-28 16:31:55,720 INFO    MainThread:3830 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 28063
  total_bytes: 28063
}

2021-09-28 16:31:55,823 INFO    MainThread:3830 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 28063
  total_bytes: 28063
}

2021-09-28 16:31:56,023 INFO    MainThread:3830 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 28063
  total_bytes: 28063
}

2021-09-28 16:31:56,609 INFO    MainThread:3830 [wandb_run.py:_wait_for_finish():1697] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 28063
  total_bytes: 28063
}
local_info {
}

2021-09-28 16:31:57,772 INFO    MainThread:3830 [wandb_run.py:_show_files():1947] logging synced files
